# build in configure for the pipeline
path:
  cutseq: /pipeline/micromamba/bin/cutseq
  samtools: /pipeline/micromamba/bin/samtools
  umicollapse: java -server -Xms8G -Xmx36G -Xss100M -jar /pipeline/UMICollapse/umicollapse.jar bam
  markduplicates: java -server -Xms8G -Xmx36G -Xss100M -jar /pipeline/gatk/gatk.jar MarkDuplicates
  hisat3n: /pipeline/hisat2-hisat-3n/hisat-3n
  hisat3nbuild: /pipeline/hisat2-hisat-3n/hisat-3n-build
  hisat3ntable: /pipeline/hisat2-hisat-3n/hisat-3n-table
  joinPileup: /pipeline/bin/join_pileup.py
  filterSites: /pipeline/bin/filter_sites.py

# can be "ECLIP10", "ECLIP6", "TAKARAV3", "SACSEQV3", "STRANDED", ...
libtype: ECLIP6
# m6A method, use A to G mutation
base_change: 'A,G'
# by default, the pipeline will force remove the PCR duplicates based on the UMI
# if UMI is not available, you can toggle the markdup to `false` to skip the PCR duplicate removal
markdup: true
# by default, the pipeline will use the strandness information from the library
# if the strandness is not available, set the strandness to `false`
strandness: true

gene_norc: true
splice_genome: true
